artifact_location: file:///E:/STUDY/MLops/PycharmFiles/MLops2024/2.MLFlow_Logging_Functions/mytracks/0
creation_time: 1707995751578
experiment_id: '0'
last_update_time: 1707995751578
lifecycle_stage: active
name: Default
